version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: quantcrux-postgres
    environment:
      POSTGRES_DB: quantcrux
      POSTGRES_USER: quantcrux
      POSTGRES_PASSWORD: quantcrux123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - quantcrux-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quantcrux"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Eureka Server
  eureka-server:
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile
    container_name: quantcrux-eureka
    ports:
      - "8761:8761"
    networks:
      - quantcrux-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Gateway Service
  gateway-service:
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    container_name: quantcrux-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - quantcrux-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Auth Service
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: quantcrux-auth
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_auth
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/auth/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Strategy Service
  strategy-service:
    build:
      context: ./backend/strategy-service
      dockerfile: Dockerfile
    container_name: quantcrux-strategy
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - quantcrux-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/quantcrux_strategy
      SPRING_DATASOURCE_USERNAME: quantcrux
      SPRING_DATASOURCE_PASSWORD: quantcrux123
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

  # Market Data Service
  market-data-service:
    build:
      context: ./backend/market-data-service
      dockerfile: Dockerfile
    container_name: quantcrux-market-data
    ports:
      - "8083:8083"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - quantcrux-network
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/

volumes:
  postgres_data:

networks:
  quantcrux-network:
    driver: bridge