server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: strategy-service
          uri: lb://strategy-service
          predicates:
            - Path=/api/strategies/**
        - id: backtest-service
          uri: lb://backtest-service
          predicates:
            - Path=/api/backtest/**
        - id: market-data-service
          uri: lb://market-data-service
          predicates:
            - Path=/api/market-data/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: portfolio-service
          uri: lb://portfolio-service
          predicates:
            - Path=/api/portfolio/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: quantcrux-secret-key-for-jwt-token-generation-and-validation